<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="9" hostname="KULANDASAMYC" name="TestCases.QAServerPatch" tests="10" failures="0" timestamp="11 Apr 2019 11:11:45 GMT" time="12.802" errors="1">
  <testcase name="executeRow9" time="12.802" classname="TestCases.QAServerPatch">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at TestCases.QAServerPatch.executeRow9(QAServerPatch.java:295)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- executeRow9 -->
  <testcase name="executeRow17" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow17 -->
  <testcase name="executeRow16" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow16 -->
  <testcase name="executeRow13" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow13 -->
  <testcase name="executeRow6" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow6 -->
  <testcase name="executeRow12" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow12 -->
  <testcase name="executeRow11" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow11 -->
  <testcase name="executeRow4" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow4 -->
  <testcase name="executeRow10" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow10 -->
  <testcase name="executeRow5" classname="TestCases.QAServerPatch">
    <skipped/>
  </testcase> <!-- executeRow5 -->
</testsuite> <!-- TestCases.QAServerPatch -->
